baseURL = "https://pr4-kp.github.io"
languageCode = "en-us"
title = "pramana's blog"
theme = "archie"
copyright = "Â© Pramana"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[Params]
mode = "toggle"
useCDN = false

[[Params.Social]]
name = "GitHub"
icon = "github"
url = "https://github.com/pr4-kp/"


[[menu.main]]
name = "all posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "about"
url = "/about"
weight = 100

# [[menu.main]]
# name = "now"
# url = "/now"
# weight = 102

[[menu.main]]
name = "tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "notes"
url = "/notes"
weight = 2

[sitemap]
changefreq = "daily"
priority = 0.5
